// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MathUtils{
	/**
	 * Returns a negative number if B is left of A, positive if it is right
	 **/
	public static float AngleDir(Vector2 A, Vector2 B)
	{
		return -A.x * B.y + A.y * B.x;
	}

	public static float AngleDir(Vector3 fwd, Vector3 targetDir, Vector3 up)
		
	{
		
		Vector3 perp = Vector3.Cross(fwd, targetDir);
		
		float dir = Vector3.Dot(perp, up);
		
		
		
		if (dir > 0.0f) {
			
			return 1.0f;
			
		} else if (dir < 0.0f) {
			
			return -1.0f;
			
		} else {
			
			return 0.0f;
			
		}
		
	}
}